#=============================================================================
# bandwidth, a benchmark to measure memory transfer bandwidth.
# Copyright (C) 2026 by Zack T Smith.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# The author may be reached at 3 at zs3 dot me.
#============================================================================*/

FROM --platform=linux/armhf debian:trixie

ENV TERM=xterm

RUN dpkg --add-architecture armhf 
RUN apt update
RUN apt install -y libc6:armhf
RUN apt install -y dialog

RUN TERM=xterm apt install -y \
  bc \
  build-essential \
  file \
  gcc \
  gdb \
  gzip \
  less \
  libncurses6 \
  man \
  nasm \
  tar \
  vim \
  wget \
  zip unzip 

WORKDIR /app

COPY . .
CMD [ "sh", "-c", "uname -m && make clean && make && echo 'To run, type ./bandwidth32' && bash"]
